### ISSUE TITLE
Errors when building Kimera-PGMO

### ISSUE THREAD

**Issue by HB-Liang** [MIT-SPARK/Hydra#36]
I am trying to compile Hydra on Ubuntu 18.04 and ROS Melodic. Following the building instruction at [https://github.com/MIT-SPARK/Hydra](url), I ran into errors when building kimera-pgmo package.
Here is what the terminal show: 
![2023-07-11 14-44-08 的屏幕截图](https://github.com/MIT-SPARK/Kimera-PGMO/assets/114042103/71bd09fb-6d4b-441c-bfd4-aaa0a9a533d8)

**Comment by nathanhhughes** [comment]
Hi, thanks for your interest in our work! It looks like you have a old version of Kimera-RPGO; you can make sure that all of your dependencies are up to date by running
```
cd /path/to/catkin_ws/src
vcs pull .
```
which pulls from all of the packages that you have in the workspace.

I'm closing this given that you have the same issue opened [here](https://github.com/MIT-SPARK/Kimera-PGMO/issues/3), and that your issue is specific to Kimera-PGMO.
